package albumfotos.entity;
// Generated 05-nov-2018 21:15:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private int idalbum;
     private String nombre;
     private Integer cantmax;
     private Date fechacreacion;

    public Album() {
    }

	
    public Album(int idalbum) {
        this.idalbum = idalbum;
    }
    public Album(int idalbum, String nombre, Integer cantmax, Date fechacreacion) {
       this.idalbum = idalbum;
       this.nombre = nombre;
       this.cantmax = cantmax;
       this.fechacreacion = fechacreacion;
    }
   
    public int getIdalbum() {
        return this.idalbum;
    }
    
    public void setIdalbum(int idalbum) {
        this.idalbum = idalbum;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCantmax() {
        return this.cantmax;
    }
    
    public void setCantmax(Integer cantmax) {
        this.cantmax = cantmax;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }




}


